# Generated by Django 5.2 on 2025-05-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booklist',
            name='original_author',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
