# Generated by Django 5.1.6 on 2025-03-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='biography',
            new_name='bio',
        ),
    ]
