# Generated by Django 5.2 on 2026-09-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_booklist_is_bookmarked_booklist_original_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
